### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by PGR-14** [portajohn/OnlyFerals#1]
Will you make a version w/out the replacements?

**Comment by FFValor** [comment]
Meaning adding the ferals to the existing game?

**Comment by FFValor** [comment]
It's possible to do so, but I don't want to, personally (feel free to do it yourself, I've tried to keep the "zombify_into"s correct per feral type, you'd just need to mess around with the spawn groups)

**Comment by PGR-14** [comment]
K
